### ISSUE TITLE
test regression from github markdown change

### ISSUE THREAD

**Issue by ilovezfs** [spotify/git-test#10]
https://github.com/spotify/git-test/commit/b5c08b45b41dcef67cc8aa668fac416dde653bb2

seems to have introduced a regression when running `brew test git-test`.

The homebrew test runs
```
  test do
    system "git", "init"
    ln_s "#{bin}/git-test", testpath
    cp "#{share}/test.sh", testpath
    chmod 0755, "test.sh"
    system "git", "add", "test.sh"
    system "git", "commit", "-m", "initial commit"
    ENV["TERM"] = "xterm"
    system "#{bin}/git-test", "-v", "HEAD", "--verify='./test.sh'"
  end
```
The failure looks like this:
```
==> /usr/local/Cellar/git-test/HEAD-6fb40ef/bin/git-test -v HEAD --verify='./test.sh'
HEAD will test 1 commits
--
--
0000 | ae14608 | 921ab32 | fail
```
Full output: https://gist.github.com/ilovezfs/a3d6b4f2ef840e1a009431f10467092a

Manually running test.sh, you get this: https://gist.github.com/ilovezfs/60bce6cd3d07200a6a8e42e1e50f8b9f

The two failed tests are from
here
```
info "Should show commit table header"
$PROJECT --clear                                >/dev/null 2>&1 ; check
$PROJECT -v --verify=true                            >out 2>err ; check
grep "^iter.*commit.*tree.*result$" out err     >/dev/null 2>&1 ; check
```
and here
```
info "Should not confuse files and branches"
$PROJECT --clear                                >/dev/null 2>&1 ; check
git checkout -b subject                         >/dev/null 2>&1 ; check
add_commit "x" "differentiate branches"         >/dev/null 2>&1 ; check
$PROJECT -v --verify=true subject ^master       >out 2>err ; check
grep "^iter.*commit.*tree.*result$" out err     >/dev/null 2>&1 ; check
```
The problem seems to be that instead of printing "iter .." it just prints "--". Looking at the commit that introduced the regression,
```
-	gettext "iter commit  tree    result"
+	gettext -- "iter | commit  | tree    | result"
```
Removing the -- causes the test to pass. I'm not sure what the intent of the -- was but it seems not to be doing the right thing.

Also in the same commit the -- is used again
```
+	gettext -- "-----|---------|---------|--------------"
```
That doesn't cause test failure, but may also be incorrect.

**Comment by aes** [comment]
Yep, this is a gettext compatility snafu. The problem ultimately stems from not having access to all the environments I'd like this to be compatible with. More closely, the double-dash is a GNU-ism for protecting arguments that look like flags. I'll look into this, but it's tricky. I'm considering a rewrite into python2 which is a git requirement anyway.
