### ISSUE TITLE
Add `v1.0.3` tag to commit 5d344d1adacbf6c482701096f140bb1cacafde16

### ISSUE THREAD

**Issue by capnslipp** [spotify/git-test#21]
This is a request to add a git tag `v1.0.3` to commit 5d344d1adacbf6c482701096f140bb1cacafde16.

Tags are necessary for GitHub to publish Releases, and also relied upon by other tools to track the latest version of `git-test`.  As it stands, the latest version of `git-test` that Homebrew can install/update-to is `v1.0.2`, since that's currently the numerically highest tag.

**Comment by aes** [comment]
Done!
