### ISSUE TITLE
Add `v1.0.4` tag to commit 3e691bbef63a0247d6383160841bf79014dff645

### ISSUE THREAD

**Issue by capnslipp** [spotify/git-test#22]
This is a request to add a git tag `v1.0.4` to commit 3e691bbef63a0247d6383160841bf79014dff645.

Tags are necessary for GitHub to publish Releases, and also relied upon by other tools to track the latest version of `git-test`.  As it stands, the latest version of `git-test` that Homebrew can install/update-to is `v1.0.2`, since that's currently the numerically highest tag.

**Comment by aes** [comment]
Done!
(Also, let me know if there's anything else, particularly around defaults and usability.)

**Comment by capnslipp** [comment]
Regarding usability, I have a couple of my own modifications that add ANSI coloring… but I wasn't planning on doing a PR until I've figured out how best to make the colors configurable and to respect non-color terminals.  I'm using `git config --get-color …` to generate the appropriate escape sequences, so there may be no big issues but… I guess I just haven't had time to look at how other modern CLI test tools handle color.

So color would be nice.  If you don't get around to it, I will eventually.
