### ISSUE TITLE
git test fails with default options when there is a file with the same name as a branch

### ISSUE THREAD

**Issue by pjknowles** [spotify/git-test#5]
% git rev-parse --abbrev-ref HEAD                                             ✭
database
% git ls-files --directory database/utilities/clone.py                        ✭
database/utilities/clone.py
% git test -v                                                                 ✭
fatal: ambiguous argument 'database': both revision and filename
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
List of commits to test is empty%

**Comment by aes** [comment]
Oh, my god, this has rotted for over a year! Why haven't I noticed this?
